apiVersion: boot.ironcore.dev/v1alpha1
kind: IPXEBootConfig
metadata:
  labels:
    app.kubernetes.io/name: ipxebootconfig
    app.kubernetes.io/instance: ipxebootconfig-sample
    app.kubernetes.io/part-of: ipxe-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ipxe-operator
  name: ipxebootconfig-sample
spec:
  systemUuid: "1234"
  systemIP: 1.2.3.4
  ignitionSecretRef:
    name: sample-ignition
